language: python
python:
  - "2.7.4"
  - "3.6"
env:
  -DJANGO=3.2 DB=mysql

 # command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
 # command to run tests
script:
  - pytest
  - coverage run -- mysource=SD-Group-24-main, ecommerce manage.py test
after_success:
  coveralls
